### ISSUE TITLE
amen_cross fails to converge after the latest tweaks

### ISSUE THREAD

**Issue by aiboyko** [oseledets/TT-Toolbox#28]
amen_cross suddenly stopped being robust, now it fails to converge on constant-like or piece-wise functions. it used to converge on these functions with 99.99% success rate before.

For example:
1) amen_cross(2 * ones(5, 1), @(x) 1, 1e-6,'nswp',40)

2) 
xhpar=@(x)abs(( x-240)/15);
xlpar=@(x)abs(( x-16)/15);
sxf2=@(x) ...
              (x      >=  240) * (1 + 1j * xhpar(x)^m * 7 )+...
              (x      <=  16) * (1 + 1j * xlpar(x)^m * 7)+...
              (x      > 16) * ( x      <240)   ;        
amen_cross(2 * ones(7, 1),@(bin) invsxf2( bi2de(bin-1) ), 1e-6)

I played with various options, it doesn't help though.

**Comment by dolgov** [comment]
Sorry for that, it was the cross/localcross.m function, which implements the full-pivoted cross on a TT block.
I made the mex version working for ones and zeros and forgot about the Matlab's one.
I have updated it.
BTW, you might want to compile fmex/localcross for your platform (is it Mac?)

Now amen_cross works for the constant.
However, the second function violates Matlab syntax (at least, in 2013b), so I could not run this test.

**Comment by aiboyko** [comment]
I'm using Windows, do I still have to compile something? because I've got no idea.

Github seems to process * symbol as italics special symbol, I've fixed the second example.

**Comment by dolgov** [comment]
You don't have to compile, it will fall back to the matlab code automatically if it does not find the mex.
It may just be slower on large matrices.
If you pull the latest version, it should work correctly now.

**Comment by aiboyko** [comment]
I'll check and get back

**Comment by aiboyko** [comment]
seems to be working
